/**
 * Country -> IANA time zone data used by the Settings timezone selector.
 *
 * Each country lists its time zones with the primary/most-populous zone first.
 * Zone strings are canonical IANA identifiers understood by `Intl.DateTimeFormat`.
 */

export type Country = {
  /** ISO 3166-1 alpha-2 code. */
  code: string;
  name: string;
  /** IANA time zones, primary zone first. */
  timezones: string[];
};

export const COUNTRIES: readonly Country[] = [
  { code: "AF", name: "Afghanistan", timezones: ["Asia/Kabul"] },
  { code: "AL", name: "Albania", timezones: ["Europe/Tirane"] },
  { code: "DZ", name: "Algeria", timezones: ["Africa/Algiers"] },
  { code: "AD", name: "Andorra", timezones: ["Europe/Andorra"] },
  { code: "AO", name: "Angola", timezones: ["Africa/Luanda"] },
  { code: "AG", name: "Antigua and Barbuda", timezones: ["America/Antigua"] },
  { code: "AR", name: "Argentina", timezones: ["America/Argentina/Buenos_Aires"] },
  { code: "AM", name: "Armenia", timezones: ["Asia/Yerevan"] },
  {
    code: "AU",
    name: "Australia",
    timezones: [
      "Australia/Sydney",
      "Australia/Melbourne",
      "Australia/Brisbane",
      "Australia/Adelaide",
      "Australia/Perth",
      "Australia/Darwin",
      "Australia/Hobart",
    ],
  },
  { code: "AT", name: "Austria", timezones: ["Europe/Vienna"] },
  { code: "AZ", name: "Azerbaijan", timezones: ["Asia/Baku"] },
  { code: "BS", name: "Bahamas", timezones: ["America/Nassau"] },
  { code: "BH", name: "Bahrain", timezones: ["Asia/Bahrain"] },
  { code: "BD", name: "Bangladesh", timezones: ["Asia/Dhaka"] },
  { code: "BB", name: "Barbados", timezones: ["America/Barbados"] },
  { code: "BY", name: "Belarus", timezones: ["Europe/Minsk"] },
  { code: "BE", name: "Belgium", timezones: ["Europe/Brussels"] },
  { code: "BZ", name: "Belize", timezones: ["America/Belize"] },
  { code: "BJ", name: "Benin", timezones: ["Africa/Porto-Novo"] },
  { code: "BT", name: "Bhutan", timezones: ["Asia/Thimphu"] },
  { code: "BO", name: "Bolivia", timezones: ["America/La_Paz"] },
  { code: "BA", name: "Bosnia and Herzegovina", timezones: ["Europe/Sarajevo"] },
  { code: "BW", name: "Botswana", timezones: ["Africa/Gaborone"] },
  {
    code: "BR",
    name: "Brazil",
    timezones: [
      "America/Sao_Paulo",
      "America/Bahia",
      "America/Fortaleza",
      "America/Recife",
      "America/Manaus",
      "America/Cuiaba",
      "America/Belem",
      "America/Rio_Branco",
      "America/Noronha",
    ],
  },
  { code: "BN", name: "Brunei", timezones: ["Asia/Brunei"] },
  { code: "BG", name: "Bulgaria", timezones: ["Europe/Sofia"] },
  { code: "BF", name: "Burkina Faso", timezones: ["Africa/Ouagadougou"] },
  { code: "BI", name: "Burundi", timezones: ["Africa/Bujumbura"] },
  { code: "KH", name: "Cambodia", timezones: ["Asia/Phnom_Penh"] },
  { code: "CM", name: "Cameroon", timezones: ["Africa/Douala"] },
  {
    code: "CA",
    name: "Canada",
    timezones: [
      "America/Toronto",
      "America/Vancouver",
      "America/Edmonton",
      "America/Winnipeg",
      "America/Halifax",
      "America/St_Johns",
      "America/Regina",
      "America/Whitehorse",
    ],
  },
  { code: "CV", name: "Cape Verde", timezones: ["Atlantic/Cape_Verde"] },
  { code: "CF", name: "Central African Republic", timezones: ["Africa/Bangui"] },
  { code: "TD", name: "Chad", timezones: ["Africa/Ndjamena"] },
  {
    code: "CL",
    name: "Chile",
    timezones: ["America/Santiago", "Pacific/Easter", "America/Punta_Arenas"],
  },
  { code: "CN", name: "China", timezones: ["Asia/Shanghai", "Asia/Urumqi"] },
  { code: "CO", name: "Colombia", timezones: ["America/Bogota"] },
  { code: "KM", name: "Comoros", timezones: ["Indian/Comoro"] },
  { code: "CG", name: "Congo (Republic)", timezones: ["Africa/Brazzaville"] },
  {
    code: "CD",
    name: "Congo (DRC)",
    timezones: ["Africa/Kinshasa", "Africa/Lubumbashi"],
  },
  { code: "CR", name: "Costa Rica", timezones: ["America/Costa_Rica"] },
  { code: "CI", name: "Côte d'Ivoire", timezones: ["Africa/Abidjan"] },
  { code: "HR", name: "Croatia", timezones: ["Europe/Zagreb"] },
  { code: "CU", name: "Cuba", timezones: ["America/Havana"] },
  { code: "CY", name: "Cyprus", timezones: ["Asia/Nicosia"] },
  { code: "CZ", name: "Czechia", timezones: ["Europe/Prague"] },
  { code: "DK", name: "Denmark", timezones: ["Europe/Copenhagen"] },
  { code: "DJ", name: "Djibouti", timezones: ["Africa/Djibouti"] },
  { code: "DM", name: "Dominica", timezones: ["America/Dominica"] },
  { code: "DO", name: "Dominican Republic", timezones: ["America/Santo_Domingo"] },
  {
    code: "EC",
    name: "Ecuador",
    timezones: ["America/Guayaquil", "Pacific/Galapagos"],
  },
  { code: "EG", name: "Egypt", timezones: ["Africa/Cairo"] },
  { code: "SV", name: "El Salvador", timezones: ["America/El_Salvador"] },
  { code: "GQ", name: "Equatorial Guinea", timezones: ["Africa/Malabo"] },
  { code: "ER", name: "Eritrea", timezones: ["Africa/Asmara"] },
  { code: "EE", name: "Estonia", timezones: ["Europe/Tallinn"] },
  { code: "SZ", name: "Eswatini", timezones: ["Africa/Mbabane"] },
  { code: "ET", name: "Ethiopia", timezones: ["Africa/Addis_Ababa"] },
  { code: "FJ", name: "Fiji", timezones: ["Pacific/Fiji"] },
  { code: "FI", name: "Finland", timezones: ["Europe/Helsinki"] },
  { code: "FR", name: "France", timezones: ["Europe/Paris"] },
  { code: "GA", name: "Gabon", timezones: ["Africa/Libreville"] },
  { code: "GM", name: "Gambia", timezones: ["Africa/Banjul"] },
  { code: "GE", name: "Georgia", timezones: ["Asia/Tbilisi"] },
  { code: "DE", name: "Germany", timezones: ["Europe/Berlin"] },
  { code: "GH", name: "Ghana", timezones: ["Africa/Accra"] },
  { code: "GR", name: "Greece", timezones: ["Europe/Athens"] },
  { code: "GD", name: "Grenada", timezones: ["America/Grenada"] },
  { code: "GT", name: "Guatemala", timezones: ["America/Guatemala"] },
  { code: "GN", name: "Guinea", timezones: ["Africa/Conakry"] },
  { code: "GW", name: "Guinea-Bissau", timezones: ["Africa/Bissau"] },
  { code: "GY", name: "Guyana", timezones: ["America/Guyana"] },
  { code: "HT", name: "Haiti", timezones: ["America/Port-au-Prince"] },
  { code: "HN", name: "Honduras", timezones: ["America/Tegucigalpa"] },
  { code: "HK", name: "Hong Kong", timezones: ["Asia/Hong_Kong"] },
  { code: "HU", name: "Hungary", timezones: ["Europe/Budapest"] },
  { code: "IS", name: "Iceland", timezones: ["Atlantic/Reykjavik"] },
  { code: "IN", name: "India", timezones: ["Asia/Kolkata"] },
  {
    code: "ID",
    name: "Indonesia",
    timezones: ["Asia/Jakarta", "Asia/Makassar", "Asia/Jayapura", "Asia/Pontianak"],
  },
  { code: "IR", name: "Iran", timezones: ["Asia/Tehran"] },
  { code: "IQ", name: "Iraq", timezones: ["Asia/Baghdad"] },
  { code: "IE", name: "Ireland", timezones: ["Europe/Dublin"] },
  { code: "IL", name: "Israel", timezones: ["Asia/Jerusalem"] },
  { code: "IT", name: "Italy", timezones: ["Europe/Rome"] },
  { code: "JM", name: "Jamaica", timezones: ["America/Jamaica"] },
  { code: "JP", name: "Japan", timezones: ["Asia/Tokyo"] },
  { code: "JO", name: "Jordan", timezones: ["Asia/Amman"] },
  {
    code: "KZ",
    name: "Kazakhstan",
    timezones: ["Asia/Almaty", "Asia/Aqtobe", "Asia/Aqtau", "Asia/Oral"],
  },
  { code: "KE", name: "Kenya", timezones: ["Africa/Nairobi"] },
  {
    code: "KI",
    name: "Kiribati",
    timezones: ["Pacific/Tarawa", "Pacific/Kiritimati", "Pacific/Kanton"],
  },
  { code: "KP", name: "North Korea", timezones: ["Asia/Pyongyang"] },
  { code: "KR", name: "South Korea", timezones: ["Asia/Seoul"] },
  { code: "KW", name: "Kuwait", timezones: ["Asia/Kuwait"] },
  { code: "KG", name: "Kyrgyzstan", timezones: ["Asia/Bishkek"] },
  { code: "LA", name: "Laos", timezones: ["Asia/Vientiane"] },
  { code: "LV", name: "Latvia", timezones: ["Europe/Riga"] },
  { code: "LB", name: "Lebanon", timezones: ["Asia/Beirut"] },
  { code: "LS", name: "Lesotho", timezones: ["Africa/Maseru"] },
  { code: "LR", name: "Liberia", timezones: ["Africa/Monrovia"] },
  { code: "LY", name: "Libya", timezones: ["Africa/Tripoli"] },
  { code: "LI", name: "Liechtenstein", timezones: ["Europe/Vaduz"] },
  { code: "LT", name: "Lithuania", timezones: ["Europe/Vilnius"] },
  { code: "LU", name: "Luxembourg", timezones: ["Europe/Luxembourg"] },
  { code: "MO", name: "Macau", timezones: ["Asia/Macau"] },
  { code: "MG", name: "Madagascar", timezones: ["Indian/Antananarivo"] },
  { code: "MW", name: "Malawi", timezones: ["Africa/Blantyre"] },
  {
    code: "MY",
    name: "Malaysia",
    timezones: ["Asia/Kuala_Lumpur", "Asia/Kuching"],
  },
  { code: "MV", name: "Maldives", timezones: ["Indian/Maldives"] },
  { code: "ML", name: "Mali", timezones: ["Africa/Bamako"] },
  { code: "MT", name: "Malta", timezones: ["Europe/Malta"] },
  { code: "MH", name: "Marshall Islands", timezones: ["Pacific/Majuro"] },
  { code: "MR", name: "Mauritania", timezones: ["Africa/Nouakchott"] },
  { code: "MU", name: "Mauritius", timezones: ["Indian/Mauritius"] },
  {
    code: "MX",
    name: "Mexico",
    timezones: [
      "America/Mexico_City",
      "America/Cancun",
      "America/Monterrey",
      "America/Tijuana",
      "America/Hermosillo",
      "America/Mazatlan",
      "America/Merida",
      "America/Chihuahua",
    ],
  },
  {
    code: "FM",
    name: "Micronesia",
    timezones: ["Pacific/Pohnpei", "Pacific/Chuuk", "Pacific/Kosrae"],
  },
  { code: "MD", name: "Moldova", timezones: ["Europe/Chisinau"] },
  { code: "MC", name: "Monaco", timezones: ["Europe/Monaco"] },
  {
    code: "MN",
    name: "Mongolia",
    timezones: ["Asia/Ulaanbaatar", "Asia/Hovd", "Asia/Choibalsan"],
  },
  { code: "ME", name: "Montenegro", timezones: ["Europe/Podgorica"] },
  { code: "MA", name: "Morocco", timezones: ["Africa/Casablanca"] },
  { code: "MZ", name: "Mozambique", timezones: ["Africa/Maputo"] },
  { code: "MM", name: "Myanmar", timezones: ["Asia/Yangon"] },
  { code: "NA", name: "Namibia", timezones: ["Africa/Windhoek"] },
  { code: "NR", name: "Nauru", timezones: ["Pacific/Nauru"] },
  { code: "NP", name: "Nepal", timezones: ["Asia/Kathmandu"] },
  { code: "NL", name: "Netherlands", timezones: ["Europe/Amsterdam"] },
  {
    code: "NZ",
    name: "New Zealand",
    timezones: ["Pacific/Auckland", "Pacific/Chatham"],
  },
  { code: "NI", name: "Nicaragua", timezones: ["America/Managua"] },
  { code: "NE", name: "Niger", timezones: ["Africa/Niamey"] },
  { code: "NG", name: "Nigeria", timezones: ["Africa/Lagos"] },
  { code: "MK", name: "North Macedonia", timezones: ["Europe/Skopje"] },
  { code: "NO", name: "Norway", timezones: ["Europe/Oslo"] },
  { code: "OM", name: "Oman", timezones: ["Asia/Muscat"] },
  { code: "PK", name: "Pakistan", timezones: ["Asia/Karachi"] },
  { code: "PW", name: "Palau", timezones: ["Pacific/Palau"] },
  { code: "PS", name: "Palestine", timezones: ["Asia/Gaza", "Asia/Hebron"] },
  { code: "PA", name: "Panama", timezones: ["America/Panama"] },
  {
    code: "PG",
    name: "Papua New Guinea",
    timezones: ["Pacific/Port_Moresby", "Pacific/Bougainville"],
  },
  { code: "PY", name: "Paraguay", timezones: ["America/Asuncion"] },
  { code: "PE", name: "Peru", timezones: ["America/Lima"] },
  { code: "PH", name: "Philippines", timezones: ["Asia/Manila"] },
  { code: "PL", name: "Poland", timezones: ["Europe/Warsaw"] },
  {
    code: "PT",
    name: "Portugal",
    timezones: ["Europe/Lisbon", "Atlantic/Madeira", "Atlantic/Azores"],
  },
  { code: "PR", name: "Puerto Rico", timezones: ["America/Puerto_Rico"] },
  { code: "QA", name: "Qatar", timezones: ["Asia/Qatar"] },
  { code: "RO", name: "Romania", timezones: ["Europe/Bucharest"] },
  {
    code: "RU",
    name: "Russia",
    timezones: [
      "Europe/Moscow",
      "Europe/Kaliningrad",
      "Europe/Samara",
      "Asia/Yekaterinburg",
      "Asia/Omsk",
      "Asia/Novosibirsk",
      "Asia/Krasnoyarsk",
      "Asia/Irkutsk",
      "Asia/Yakutsk",
      "Asia/Vladivostok",
      "Asia/Magadan",
      "Asia/Kamchatka",
    ],
  },
  { code: "RW", name: "Rwanda", timezones: ["Africa/Kigali"] },
  { code: "KN", name: "Saint Kitts and Nevis", timezones: ["America/St_Kitts"] },
  { code: "LC", name: "Saint Lucia", timezones: ["America/St_Lucia"] },
  {
    code: "VC",
    name: "Saint Vincent and the Grenadines",
    timezones: ["America/St_Vincent"],
  },
  { code: "WS", name: "Samoa", timezones: ["Pacific/Apia"] },
  { code: "SM", name: "San Marino", timezones: ["Europe/San_Marino"] },
  { code: "ST", name: "Sao Tome and Principe", timezones: ["Africa/Sao_Tome"] },
  { code: "SA", name: "Saudi Arabia", timezones: ["Asia/Riyadh"] },
  { code: "SN", name: "Senegal", timezones: ["Africa/Dakar"] },
  { code: "RS", name: "Serbia", timezones: ["Europe/Belgrade"] },
  { code: "SC", name: "Seychelles", timezones: ["Indian/Mahe"] },
  { code: "SL", name: "Sierra Leone", timezones: ["Africa/Freetown"] },
  { code: "SG", name: "Singapore", timezones: ["Asia/Singapore"] },
  { code: "SK", name: "Slovakia", timezones: ["Europe/Bratislava"] },
  { code: "SI", name: "Slovenia", timezones: ["Europe/Ljubljana"] },
  { code: "SB", name: "Solomon Islands", timezones: ["Pacific/Guadalcanal"] },
  { code: "SO", name: "Somalia", timezones: ["Africa/Mogadishu"] },
  { code: "ZA", name: "South Africa", timezones: ["Africa/Johannesburg"] },
  { code: "SS", name: "South Sudan", timezones: ["Africa/Juba"] },
  {
    code: "ES",
    name: "Spain",
    timezones: ["Europe/Madrid", "Atlantic/Canary"],
  },
  { code: "LK", name: "Sri Lanka", timezones: ["Asia/Colombo"] },
  { code: "SD", name: "Sudan", timezones: ["Africa/Khartoum"] },
  { code: "SR", name: "Suriname", timezones: ["America/Paramaribo"] },
  { code: "SE", name: "Sweden", timezones: ["Europe/Stockholm"] },
  { code: "CH", name: "Switzerland", timezones: ["Europe/Zurich"] },
  { code: "SY", name: "Syria", timezones: ["Asia/Damascus"] },
  { code: "TW", name: "Taiwan", timezones: ["Asia/Taipei"] },
  { code: "TJ", name: "Tajikistan", timezones: ["Asia/Dushanbe"] },
  { code: "TZ", name: "Tanzania", timezones: ["Africa/Dar_es_Salaam"] },
  { code: "TH", name: "Thailand", timezones: ["Asia/Bangkok"] },
  { code: "TL", name: "Timor-Leste", timezones: ["Asia/Dili"] },
  { code: "TG", name: "Togo", timezones: ["Africa/Lome"] },
  { code: "TO", name: "Tonga", timezones: ["Pacific/Tongatapu"] },
  {
    code: "TT",
    name: "Trinidad and Tobago",
    timezones: ["America/Port_of_Spain"],
  },
  { code: "TN", name: "Tunisia", timezones: ["Africa/Tunis"] },
  { code: "TR", name: "Turkey", timezones: ["Europe/Istanbul"] },
  { code: "TM", name: "Turkmenistan", timezones: ["Asia/Ashgabat"] },
  { code: "TV", name: "Tuvalu", timezones: ["Pacific/Funafuti"] },
  { code: "UG", name: "Uganda", timezones: ["Africa/Kampala"] },
  { code: "UA", name: "Ukraine", timezones: ["Europe/Kyiv"] },
  { code: "AE", name: "United Arab Emirates", timezones: ["Asia/Dubai"] },
  { code: "GB", name: "United Kingdom", timezones: ["Europe/London"] },
  {
    code: "US",
    name: "United States",
    timezones: [
      "America/New_York",
      "America/Chicago",
      "America/Denver",
      "America/Los_Angeles",
      "America/Phoenix",
      "America/Anchorage",
      "Pacific/Honolulu",
      "America/Detroit",
      "America/Indiana/Indianapolis",
    ],
  },
  { code: "UY", name: "Uruguay", timezones: ["America/Montevideo"] },
  {
    code: "UZ",
    name: "Uzbekistan",
    timezones: ["Asia/Tashkent", "Asia/Samarkand"],
  },
  { code: "VU", name: "Vanuatu", timezones: ["Pacific/Efate"] },
  { code: "VA", name: "Vatican City", timezones: ["Europe/Vatican"] },
  { code: "VE", name: "Venezuela", timezones: ["America/Caracas"] },
  { code: "VN", name: "Vietnam", timezones: ["Asia/Ho_Chi_Minh"] },
  { code: "YE", name: "Yemen", timezones: ["Asia/Aden"] },
  { code: "ZM", name: "Zambia", timezones: ["Africa/Lusaka"] },
  { code: "ZW", name: "Zimbabwe", timezones: ["Africa/Harare"] },
];

const COUNTRY_BY_CODE = new Map(COUNTRIES.map((c) => [c.code, c]));

/** All time zones known to this dataset — used to validate persisted values. */
export const KNOWN_TIMEZONES: ReadonlySet<string> = new Set(
  COUNTRIES.flatMap((c) => c.timezones),
);

export function getCountry(code: string | null | undefined): Country | undefined {
  if (!code) return undefined;
  return COUNTRY_BY_CODE.get(code);
}

export function isKnownCountry(code: string | null | undefined): boolean {
  return Boolean(code) && COUNTRY_BY_CODE.has(code as string);
}

/**
 * Turns an ISO 3166-1 alpha-2 code into its flag emoji (regional indicators).
 * Returns an empty string for anything that is not a two-letter code.
 */
export function flagEmoji(code: string): string {
  if (!/^[A-Za-z]{2}$/.test(code)) return "";
  return code
    .toUpperCase()
    .replace(/./g, (char) =>
      String.fromCodePoint(127397 + char.charCodeAt(0)),
    );
}

/** Renders an IANA zone id as a friendlier label, e.g. "America/New_York" -> "New York". */
export function timezoneLabel(timezone: string): string {
  const city = timezone.split("/").pop() ?? timezone;
  return city.replace(/_/g, " ");
}
